from __future__ import annotations

# Standard Tier-1 Venues for Computer Science / ML / Systems
TOP_VENUES = [v.upper() for v in [
    # --- Computer Science Conferences & Acronyms ---
    "ICSE", "FSE", "ESEC", "ASE", "ISSTA", "PLDI", "POPL", "OOPSLA",
    "SOSP", "OSDI", "USENIX", "NSDI", "SIGCOMM", "MOBICOM", "MOBISYS", "INFOCOM",
    "SIGMOD", "VLDB", "ICDE", "PODS", "NEURIPS", "NIPS", "ICML", "ICLR", "AAAI", "IJCAI",
    "CVPR", "ICCV", "ECCV", "ACL", "EMNLP", "NAACL", "COLING",
    "KDD", "WWW", "THE WEB CONFERENCE", "WSDM", "SIGIR", "CIKM",
    "CCS", "IEEE S&P", "OAKLAND", "NDSS", "CRYPTO", "EUROCRYPT", "ASIACRYPT",
    "CHI", "UIST", "CSCW", "UBICOMP", "DAC", "DATE", "MICRO", "ISCA", "HPCA",
    "SC", "IPDPS", "PPOPP", "ICRA", "IROS", "RSS", "SIGGRAPH",

    # --- Computer Science Journals & Spelled-out Names ---
    "TSE", "TOSEM", "TOPLAS", "JACM", "CACM", "TPAMI", "TNNLS", "TKDE", "TOCS", "JMLR", "TDSC", "TNSM",
    "TRANSACTIONS ON SOFTWARE ENGINEERING",
    "TRANSACTIONS ON SOFTWARE ENGINEERING AND METHODOLOGY",
    "TRANSACTIONS ON PATTERN ANALYSIS AND MACHINE INTELLIGENCE",
    "TRANSACTIONS ON NEURAL NETWORKS AND LEARNING SYSTEMS",
    "TRANSACTIONS ON KNOWLEDGE AND DATA ENGINEERING",
    "TRANSACTIONS ON COMPUTER SYSTEMS",
    "JOURNAL OF THE ACM", "COMMUNICATIONS OF THE ACM",
    "VLDB JOURNAL", "ARTIFICIAL INTELLIGENCE", "MACHINE LEARNING",
    "JOURNAL OF MACHINE LEARNING RESEARCH", "ACM COMPUTING SURVEYS",
    "TRANSACTIONS ON DEPENDABLE AND SECURE COMPUTING",
    "TRANSACTIONS ON NETWORK AND SERVICE MANAGEMENT",

    # --- Mathematics ---
    "ANNALS OF MATHEMATICS", "INVENTIONES MATHEMATICAE", "ACTA MATHEMATICA",
    "JOURNAL OF THE AMERICAN MATHEMATICAL SOCIETY", "DUKE MATHEMATICAL JOURNAL",
    "ADVANCES IN MATHEMATICS", "COMMUNICATIONS ON PURE AND APPLIED MATHEMATICS", "MATHEMATISCHE ANNALEN",

    # --- Statistics ---
    "ANNALS OF STATISTICS", "JOURNAL OF THE ROYAL STATISTICAL SOCIETY",
    "JOURNAL OF THE AMERICAN STATISTICAL ASSOCIATION", "BIOMETRIKA", "STATISTICAL SCIENCE",

    # --- Physics ---
    "PHYSICAL REVIEW LETTERS", "PHYSICAL REVIEW X", "NATURE PHYSICS", "REVIEWS OF MODERN PHYSICS",
    "JOURNAL OF HIGH ENERGY PHYSICS", "APPLIED PHYSICS LETTERS",
    "PHYSICAL REVIEW A", "PHYSICAL REVIEW B", "PHYSICAL REVIEW C", "PHYSICAL REVIEW D", "PHYSICAL REVIEW E",

    # --- Chemistry ---
    "JOURNAL OF THE AMERICAN CHEMICAL SOCIETY", "ANGEWANDTE CHEMIE", "CHEMICAL REVIEWS",
    "NATURE CHEMISTRY", "ACS NANO", "NANO LETTERS", "CHEM", "ADVANCED MATERIALS",

    # --- Biology & Medicine ---
    "CELL", "NATURE BIOTECHNOLOGY", "NATURE GENETICS", "NATURE CELL BIOLOGY", "MOLECULAR CELL",
    "GENOME RESEARCH", "GENES & DEVELOPMENT", "EMBO JOURNAL", "NEW ENGLAND JOURNAL OF MEDICINE",
    "THE LANCET", "JAMA", "BMJ", "NATURE MEDICINE", "THE LANCET ONCOLOGY", "ANNALS OF INTERNAL MEDICINE", "PLOS MEDICINE",

    # --- Engineering & Materials ---
    "IEEE TRANSACTIONS ON INDUSTRIAL ELECTRONICS", "IEEE TRANSACTIONS ON POWER SYSTEMS",
    "IEEE TRANSACTIONS ON SMART GRID", "IEEE TRANSACTIONS ON SIGNAL PROCESSING",
    "IEEE TRANSACTIONS ON COMMUNICATIONS", "IEEE TRANSACTIONS ON CONTROL SYSTEMS TECHNOLOGY",
    "AUTOMATICA", "CONTROL ENGINEERING PRACTICE", "NATURE MATERIALS", "ADVANCED FUNCTIONAL MATERIALS",
    "ACTA MATERIALIA", "MATERIALS TODAY", "PROGRESS IN MATERIALS SCIENCE",

    # --- Electrical, Mechanical, Civil Engineering ---
    "ISSCC", "IEDM", "VLSI SYMPOSIUM", "APCCAS", "ISCAS", "RFIC SYMPOSIUM",
    "ASME JOURNAL OF MECHANICAL DESIGN", "ASME JOURNAL OF MANUFACTURING SCIENCE AND ENGINEERING",
    "INTERNATIONAL JOURNAL OF MACHINE TOOLS AND MANUFACTURE", "MECHANISM AND MACHINE THEORY",
    "JOURNAL OF STRUCTURAL ENGINEERING", "ENGINEERING STRUCTURES", "CEMENT AND CONCRETE RESEARCH", "AUTOMATION IN CONSTRUCTION",

    # --- Economics, Finance & Management ---
    "AMERICAN ECONOMIC REVIEW", "ECONOMETRICA", "QUARTERLY JOURNAL OF ECONOMICS",
    "JOURNAL OF POLITICAL ECONOMY", "REVIEW OF ECONOMIC STUDIES", "JOURNAL OF FINANCE",
    "JOURNAL OF FINANCIAL ECONOMICS", "REVIEW OF FINANCIAL STUDIES", "ACADEMY OF MANAGEMENT JOURNAL",
    "ACADEMY OF MANAGEMENT REVIEW", "STRATEGIC MANAGEMENT JOURNAL", "MANAGEMENT SCIENCE", "ORGANIZATION SCIENCE",

    # --- Psychology & Environmental Science ---
    "PSYCHOLOGICAL SCIENCE", "ANNUAL REVIEW OF PSYCHOLOGY", "JOURNAL OF PERSONALITY AND SOCIAL PSYCHOLOGY",
    "COGNITION", "NATURE CLIMATE CHANGE", "GLOBAL CHANGE BIOLOGY", "ENVIRONMENTAL SCIENCE & TECHNOLOGY", "JOURNAL OF CLEANER PRODUCTION",

    # --- Earth & Space Sciences ---
    "NATURE GEOSCIENCE", "GEOPHYSICAL RESEARCH LETTERS", "EARTH AND PLANETARY SCIENCE LETTERS",
    "THE ASTROPHYSICAL JOURNAL", "ASTRONOMY & ASTROPHYSICS",

    # --- General High-Impact Journals ---
    "NATURE", "SCIENCE", "PNAS", "NATURE COMMUNICATIONS", "SCIENTIFIC REPORTS"
]]